document.write( '<div class=\"header\">\n' );
document.write( '		<img class=\"icon\" src=\"https://antisocialnorm.net/ASN_Rat.png\" alt=\"RAT\">\n' );
document.write( '		<div class=\"navbar\">\n' );
document.write( '			<a class=\"navbar-item\" href=\"ASN-HomePage.html\">HOME</a>\n' );
document.write( '			<a class=\"navbar-item\" href=\"\">FAQ</a>\n' );
document.write( '			<a class=\"navbar-item\" href=\"\">BOT CONTROL</a>\n' );
document.write( '			<div class=\"navbar-dropdown\">\n' );
document.write( '				<a class=\"navbar-item\">ABOUT US</a>\n' );
document.write( '				<div>\n' );
document.write( '					<div>\n' );
document.write( '						<a>Server History</a>\n' );
document.write( '						<a>Logan</a>\n' );
document.write( '						<a>Michael</a>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '			<a class=\"navbar-item\" href=\"\">CONTACT US</a>\n' );
document.write( '\n' );
document.write( '			<a class=\"navbar-item\" id=\"active\" style=\"float:right;right:50px;position:relative;\" href=\"ASN-LoginPage.html\">LOGIN</a>\n' );
document.write( '			<a class=\"navbar-item\" style=\"float:right;right:50px;position:relative;\" href=\"\">UserProfile</a>\n' );
document.write( '		</div>\n' );
document.write( '	</div>' );
